<a href="https://colab.research.google.com/github/nokutungwa/PyTorch/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np
#python lists
my_list = [[1,2,3,4,5],[1,2,3,4]]
my_list
np1 = np.random.rand(3,4)
np1
tensor_2d = torch.randn(3,4)
tensor_2d
tensor_3d = torch.zeros(3,3,4)
tensor_3d
# create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor


tensor([[0.6320, 0.7186, 0.6580, 0.0498],
        [0.4669, 0.1837, 0.9906, 0.3576],
        [0.9359, 0.9385, 0.6347, 0.3998]], dtype=torch.float64)

In [2]:
#tensor operations
import torch
my_torch = torch.arange(10)
my_torch

#reshape and view
my_torch = my_torch.reshape(2,5)
my_torch
#reshape if we dont know the number of items using -1
my_torch2 = torch.arange(10)
my_torch2 = my_torch2.reshape(2,-1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [17]:
import torch
mytorch = torch.arange(20)
mytorch

mytorch = mytorch.reshape(5,-1)
mytorch


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])